### ISSUE TITLE
Cannot find errors when installing

### ISSUE THREAD

**Issue by Brawrdon** [florentpoujol/superpowers-game-fgui-plugin#1]
After installing the fGui plugin, this error is produced even before I start to write any code.
I'm using Superpowers v0.19.0 but the error also occurred on v0.18.0

![Imgur](http://i.imgur.com/LAuIF5Y.png)

**Comment by florentpoujol** [comment]
Hello

You need the DOM plugin, too.
https://github.com/florentpoujol/superpowers-game-dom-plugin

It expose to Typescript all HTML object and types which are currently missing.
Sorry that it's not in the readme, I will fix that.

**Comment by Brawrdon** [comment]
Thanks, it all works now!
